version: '3.4'

services:
    gateway:
        image: nginx:latest
        container_name: gateway
        ports:
          - "80:80"
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
          - inventorymanagementsystem.microservices.inventory.api
          - inventorymanagementsystem.microservices.purchase.api

    sql.inventory.management.server:
        image: mcr.microsoft.com/mssql/server
        container_name: sql.inventory.management.server
        environment: 
            SA_PASSWORD: SebasCaro454
            ACCEPT_EULA: "Y"
        ports:
            - "8006:1433"
        volumes:
            - db-data:/var/opt/mssql

    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=SC45
            - RABBITMQ_DEFAULT_PASS=4545@
        ports:
            - "5672:5672"
            - "15672:15672"

    inventorymanagementsystem.microservices.inventory.api:
        image: ${DOCKER_REGISTRY-}inventorymanagementsystemmicroservicesinventory
        container_name: microservices.inventory.api
        build:
            context: .
            dockerfile: InventoryManagementSystem.Microservices.Inventory.API/Dockerfile
        ports:
            - "8007:8007"
        environment:
            - HOSTNAME=rabbitmq
            - RBMQ_USERNAME=SC45
            - RBMQ_PASSWORD=4545@
            - DB_ConnectionString=Data Source=sql.inventory.management.server;Initial Catalog=InventorySystem;User ID=sa;Password=SebasCaro454;TrustServerCertificate=True;
        depends_on:
            - rabbitmq
            - sql.inventory.management.server
    
    inventorymanagementsystem.microservices.purchase.api:
        image: ${DOCKER_REGISTRY-}inventorymanagementsystemmicroservicespurchaseapi
        container_name: microservices.purchase.api
        build:
            context: .
            dockerfile: InventoryManagementSystem.Microservices.Purchase.API/Dockerfile
        ports:
            - "8008:8008"
        environment:
            - HOSTNAME=rabbitmq
            - RBMQ_USERNAME=SC45
            - RBMQ_PASSWORD=4545@
            - DB_ConnectionString=Data Source=sql.inventory.management.server;Initial Catalog=InventorySystem;User ID=sa;Password=SebasCaro454;TrustServerCertificate=True;
        depends_on:
            - rabbitmq
            - sql.inventory.management.server
            - inventorymanagementsystem.microservices.inventory.api

networks:
    default:
        driver: bridge

volumes:
    db-data:
